# Generated by Django 3.2.9 on 2022-03-13 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_projects', '0008_foodproject_primary_app_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('EXECUTION', 'Execution'), ('DONE', 'Done')], default='WAITING', max_length=120)),
                ('menu_items', models.ManyToManyField(to='food_projects.MenuItem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_projects.foodproject')),
                ('promotions', models.ManyToManyField(to='food_projects.PromotionItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
