# Generated by Django 3.2.9 on 2022-03-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_time',
            field=models.TimeField(default='11:00'),
            preserve_default=False,
        ),
    ]
