# Generated by Django 3.2.9 on 2022-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0008_foodproject_primary_app_color'),
        ('card', '0002_order_preferred_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='food_projects.MenuItem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='food_projects.PromotionItem'),
        ),
    ]
