# Generated by Django 3.2.9 on 2022-03-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_ordermenuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenuitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_menu_items', to='card.order'),
        ),
    ]
