# Generated by Django 3.2.9 on 2022-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_lolkekmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lolkekmodel',
            name='lol_kek_field',
            field=models.CharField(default=22, max_length=120),
            preserve_default=False,
        ),
    ]
