# Generated by Django 3.2.9 on 2022-03-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_auto_20220325_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenuitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_menu_items', to='card.order'),
        ),
        migrations.AlterField(
            model_name='orderpromotions',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_promotions', to='card.order'),
        ),
    ]
