# Generated by Django 3.2.9 on 2022-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0014_auto_20220507_2157'),
        ('card', '0012_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenuitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='food_projects.MenuOption'),
        ),
        migrations.AddField(
            model_name='orderpromotions',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='food_projects.MenuOption'),
        ),
    ]
