# Generated by Django 3.2.9 on 2022-02-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_projects', '0002_foodproject_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproject',
            name='owner',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
