# Generated by Django 3.2.9 on 2022-03-06 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0005_foodproject_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('menu_items', models.ManyToManyField(to='food_projects.MenuItem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_projects.foodproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
