# Generated by Django 3.2.9 on 2022-03-07 11:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0007_foodproject_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproject',
            name='primary_app_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
