# Generated by Django 3.2.9 on 2022-03-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0008_foodproject_primary_app_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionitem',
            name='over_image_text_color',
            field=models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black')], default='WHITE', max_length=20),
            preserve_default=False,
        ),
    ]
