# Generated by Django 3.2.9 on 2022-05-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0011_menuoption_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='options',
            new_name='allowed_options',
        ),
        migrations.RenameField(
            model_name='promotionitem',
            old_name='options',
            new_name='allowed_options',
        ),
    ]
