# Generated by Django 3.2.9 on 2022-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0012_auto_20220507_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='allowed_options',
            field=models.ManyToManyField(default=None, null=True, to='food_projects.MenuOption'),
        ),
        migrations.AlterField(
            model_name='promotionitem',
            name='allowed_options',
            field=models.ManyToManyField(default=None, null=True, to='food_projects.MenuOption'),
        ),
    ]
