# Generated by Django 3.2.9 on 2022-05-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0015_foodproject_linkto2gis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodproject',
            old_name='linkTo2Gis',
            new_name='link_to_2gis',
        ),
    ]
