# Generated by Django 3.2.9 on 2022-05-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0017_auto_20220514_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemtype',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_projects.foodproject'),
            preserve_default=False,
        ),
    ]
