# Generated by Django 3.2.9 on 2022-05-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0019_auto_20220516_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproject',
            name='app_icon_asset',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
