# Generated by Django 3.2.9 on 2022-03-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_projects', '0007_foodproject_address'),
        ('user', '0002_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_projects.foodproject'),
        ),
    ]
